let usr_name = [
    "Mausam Kumar",
    "Abhishek Kumar",
    "Aditya Kumar",
    "Ayushman Pratap Singh",
    "Arjun",
    "Dinesh Kumar",
    "Sunita Yadav",
    "Aryan Singh",
    "Anand Kumar Soni",
    "Jyoti Chaudhary",
    "Arpit Singh",
    "Dheeraj Kushwaha",
    "Santosh Chauhan",
    "Shivang Bhatt",
    "Shalu Yadav",
    "Miheer Jaiswal",
    "Kushagra Dixit",
    "Ashish Yadav",
    "Abhishek Singh Yadav",
    "Shivajeet Yadav",
    "Vishwajeet Yadav",
    "Aditya Prajapati",
    "Aman Gautam",
    "Ujjwal Sharma",
    "Anchal Gupta",
    "Ankit Nishad",
    "Sakshi Mishra",
    "Parul Mishra",
    "Khushi Tripathi",
    "Abhinay Pandey",
    "Aditya Singh",
    "Jatin Shukla",
    "Deepak Soni",
    "Ravi Agrahari",
    "Nripendra Pandey",
    "Aman Singh",
    "Vipin Mishra",
    "Shivansh Ojha",
    "KK Shukla",
    "Arun Singh Yadav",
    "Hemanth Pandey",
    "Tulsi Kumar Yadav",
    "Ashish Kumar Yadav",
    "Sangam Kushwaha",
    "Akriti Pandey",
    "Akriti Singh",
    "Shivji Yadav",
    "Vishal Soni",
    "Shivam Patel",
    "Manshi Kashyap"
]

let usr_handle = [
    "@mjmausam1012",
    "@abhi_8296",
    "@rahul_roy_aditya",
    "@ayushman_912",
    "@arjun",
    "@kartikey",
    "@alex.sunita",
    "@kshtriya",
    "@anand_soni",
    "@jyoti",
    "@arpit_501",
    "@sexy_puja",
    "@chauhan_santosh",
    "@pandit_shivang",
    "@shalu_882",
    "@its_prince",
    "@kushagra_dixit",
    "@yadav_ji",
    "@abhishek_yadav",
    "@yadav_shilajeet",
    "@vishwajeet_829",
    "@i_am_punnit",
    "@aman_gautam",
    "@ujjwal_sharma",
    "@anchal_64",
    "@ankit_nishad",
    "@autophile_01",
    "@parul_mishra",
    "@khushi_tripathi",
    "@abhinay",
    "@adi__",
    "@shukla_jatin__",
    "@anjali_deepak",
    "@agrahari_ravi",
    "@nripendra_pandey",
    "@aman_singh",
    "@vipin_mishra",
    "@shivanshojha",
    "@kk_shukla",
    "@arun_singh",
    "@hemanth_baba",
    "@tulsi",
    "@ashish_kumar_yadav",
    "@sangam",
    "@pandey_akriti",
    "@akriti_singh",
    "@shivji",
    "@vishal_892",
    "@patel_shivam",
    "@manshi_kashyap"
]

let usr_post = [
    "Good friends are like stars. You do not always see them, but you know they are always there.",
    "Friendship is a mercury drop. If it is dropped. Impossible to recollect. So do not drop your friends!!!!",
    "Onward and Upward!  To Narnia and the North!",
    "Onward and Upward!  To Narnia and the North!",
    "It's not the size of the dog in the fight, but the size of the fight in the dog.",
    "A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing.",
    "The great growling engine of change - technology.",
    "A man who treats his woman like a princess is proof that he has been born and raised in the arms of a queen.",
    "Worry about your character, not your reputation. Your character is who you are, your reputation is who people think you are.",
    "I am who I am, Your approval is not needed",
    "The only easy day was yesterday.",
    "We have more media than ever and more technology in our lives. It's supposed to help us communicate, but it has the opposite effect of isolating us.",
    "Sharing is good, and with digital technology, sharing is easy.",
    "She is a friend of my mind. She gather me, man. The pieces I am, she gather them and give them back to me in all the right order.",
    "It's not a faith in technology. It's faith in people.",
    "Before you diagnose yourself with depression or low self-esteem, first make sure that you are not, in fact, just surrounded by assholes.",
    "Reading more books will only confuse you more and you will be dreaming about success instead of becoming successful yourself.",
    "Technology, like art, is a soaring exercise of the human imagination.",
    "At the end of the day, the most overwhelming key to a child's success is the positive involvement of parents.",
    "Xcuse me, I found something under my shoes. Oh its your attitude.",
    "You will never know what you are capable of until you take that first step and go for it.",
    "We have more media than ever and more technology in our lives. It's supposed to help us communicate, but it has the opposite effect of isolating us.",
    "Technology without hatred can be a blessing. Technology with hatred is always a disaster.",
    "A life spent making mistakes is not only more honorable, but more useful than a life spent doing nothing.",
    "Just saw the most smartest person when i was in front of the mirror",
    "Where there is ruin, there is hope for a treasure.",
    "Nature gives to every time and season some beauties of its own; and from morning to night, as from the cradle to the grave, it is but a succession of changes so gentle and easy that we can scarcely mark their progress.",
    "Somebody asked me to explain the relationship between you and me, they expected the answer as, just friends. But I simply smiled and said. Gods gift.",
    "Why are we, as a nation so obsessed with foreign things? Is it a legacy of our colonial years? We want foreign television sets. We want foreign shirts. We want foreign technology. Why this obsession with everything imported?",
    "I quit being afraid when my first venture failed and the sky didn't fall down.",
]